import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:redbox/game/round.dart';

void main(List<String> arguments) {
  final seed = arguments.isEmpty
      ? defaultPatternSeed
      : int.parse(arguments.first);
  const levels = [1, 2, 3, 4, 5, 50, 70, 100, 1000];
  final cards = StringBuffer();
  final samples = <Map<String, Object>>[];
  for (final level in levels) {
    final round = RoundGenerator(
      patternSeed: seed,
      random: Random(seed + level),
    ).generate(level);
    final layout = round.layout;
    final data = <String, Object>{
      'level': level,
      'seed': seed,
      'name': layout.name,
      'columns': layout.columns,
      'rows': layout.rows,
      'boxes': layout.boxCount,
      'redCount': round.redIds.length,
      'mask': layout.mask,
      'redIds': round.redIds.toList()..sort(),
    };
    samples.add(data);
    stdout.writeln(
      'Level $level · ${layout.name} · ${layout.boxCount} boxes · ${round.redIds.length} red',
    );
    stdout.writeln(layout.mask.join('\n'));
    final cells = StringBuffer();
    const tile = 39;
    const gap = 10;
    final width = layout.columns * (tile + gap) - gap;
    final height = layout.rows * (tile + gap) - gap + 5;
    for (var index = 0; index < layout.slots.length; index++) {
      final id = layout.slots[index];
      if (id == null) continue;
      final x = index % layout.columns * (tile + gap);
      final y = index ~/ layout.columns * (tile + gap);
      final red = round.redIds.contains(id);
      cells.write(
        '<g class="${red ? 'remembered' : 'safe'}"><rect class="depth" x="$x" y="${y + 5}" width="$tile" height="$tile" rx="9"/><rect class="face" x="$x" y="$y" width="$tile" height="$tile" rx="9"/></g>',
      );
    }
    cards.write(
      '''<article><header><span>LEVEL ${level.toString().padLeft(2, '0')}</span><b>${round.redIds.length} to remember</b></header><div class="board"><svg viewBox="0 0 $width $height" role="img" aria-label="${layout.name}, ${layout.boxCount} square boxes">$cells</svg></div><h2>${layout.name}</h2><p>${layout.boxCount} boxes · ${round.safeCount} satisfying taps</p></article>''',
    );
  }
  final html =
      '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Red Box · Pattern sampler</title><style>
@font-face{font-family:Fredoka;src:url('../assets/fonts/Fredoka.ttf')}@font-face{font-family:Nunito;src:url('../assets/fonts/Nunito.ttf')}
*{box-sizing:border-box}body{margin:0;background:#fff8ed;color:#40342e;font-family:Nunito,sans-serif;padding:40px 24px}main{max-width:1060px;margin:auto}.intro{display:flex;align-items:center;justify-content:space-between;gap:30px;margin-bottom:30px}h1,h2{font-family:Fredoka,sans-serif;font-weight:500}h1{font-size:40px;letter-spacing:-1px;margin:0 0 12px}p{margin:0;color:#806d5c;line-height:1.6}.intro p{font-size:16px;max-width:660px}.seed{font-size:12px;margin-top:12px}button{background:#ed6258;color:#fffaf4;border:0;border-radius:15px;box-shadow:0 4px #c6413a;padding:16px 18px;font:800 15px Nunito;cursor:pointer;flex-shrink:0;min-height:48px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}article{background:#fffcf5;border:1px solid #ecdfce;border-radius:24px;padding:21px 22px;box-shadow:0 5px #eee2d2}article header{display:flex;justify-content:space-between;gap:6px;font-size:11px;font-weight:800;letter-spacing:.5px;color:#806d5c}header b{letter-spacing:0;color:#806d5c}.board{height:246px;display:flex;align-items:center;justify-content:center;margin:14px 0 0}.board svg{max-width:235px;max-height:235px;width:100%;overflow:visible}.face{fill:#f0e6d6}.depth{fill:#ddceba}.reveal .remembered .face{fill:#ed6258}.reveal .remembered .depth{fill:#c6413a}h2{font-size:22px;margin:14px 0 3px}article p{font-size:12px}footer{color:#806d5c;font-size:13px;text-align:center;padding-top:30px}@media(max-width:800px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.intro{align-items:flex-start;flex-direction:column}h1{font-size:32px}}@media(max-width:510px){body{padding:26px 18px}.grid{grid-template-columns:1fr}}
</style><main><div class="intro"><div><h1>More shapes. Little moments.</h1><p>Enjoy the tapping. The pattern changes from the start; the red boxes keep the memory challenge gentle.</p><p class="seed">Seed $seed · generated by the same Dart function as the game</p></div><button type="button" aria-pressed="false" id="reveal">Show red boxes</button></div><section class="grid" aria-label="Seeded level patterns">$cards</section><footer>Same level + seed = same shape. Retries choose fresh red positions.<br>Early levels remember one box; later levels mix one, two, and three. No rush.</footer></main><script>document.querySelector('#reveal').addEventListener('click',function(){const show=document.body.classList.toggle('reveal');this.textContent=show?'Hide red boxes':'Show red boxes';this.setAttribute('aria-pressed',String(show));});</script></html>''';
  Directory('design').createSync(recursive: true);
  File('design/patterns.html').writeAsStringSync(html);
  File('design/pattern-samples.json')
      .writeAsStringSync(const JsonEncoder.withIndent('  ').convert(samples));
}
